apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: default
spec:
  selector:
    app: orchestrator
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-depl
  namespace: default
  labels:
    app: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: bobput/demo-orchestrator:latest
