apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: default
spec:
  selector:
    app: ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-depl
  namespace: default
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: bobput/demo-ui-1:94ea7d09bc27ec8ab1e0d4f4bedc1db69f7d6d86
          ports:
            - containerPort: 80
              name: ui
          env:
            - name: POSTS_API
              valueFrom:
                configMapKeyRef:
                  name: ui-configmap
                  key: POSTS_API
            - name: USER_API
              valueFrom:
                configMapKeyRef:
                  name: ui-configmap
                  key: USER_API
            - name: COMMENTS_API
              valueFrom:
                configMapKeyRef:
                  name: ui-configmap
                  key: COMMENTS_API
            - name: AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: ui-configmap
                  key: AUTH_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configmap
data:
  # Add your key-value pairs here
  POSTS_API: http://orchestrator-service/getPosts
  USER_API: http://orchestrator-service/getUser
  COMMENTS_API: http://orchestrator-service/getComments
  AUTH_TOKEN: { { AUTH_TOKEN } }
