apiVersion: v1
kind: Service
metadata:
  name: comments-service
  namespace: default
spec:
  selector:
    app: comments
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
  namespace: default
  labels:
    app: comments
spec:
  selector:
    matchLabels:
      app: comments
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: bobput/demo-comments-1:latest
