apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  namespace: default
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: bobput/demo-get-user-1:latest
